# Site settings
title: blog
email: biaopiao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shaoting Gu | designer & developer
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://gushaoting.com" # the base hostname & protocol for your site
github_username:  biaopiao

# Build settings
markdown: kramdown
encoding: utf-8
highligher: pygments
